import os
import sys
# global ROOT_DIR, APP_DIR, BASEVIEW_DIR, BUSINESSVIEWS_DIR, COMMOMS_DIR, CONFIGS_DIR, DATAS_DIR, LOG_DIR, REPORTS_DIR, SCREENSHOTS_DIR, TEST_CASES_DIR, TEST_RUN_DIR, TESTS_DIR
ROOT_DIR = os.path.dirname(__file__)
APPS_DIR = ROOT_DIR + '/APPS'
BASEVIEW_DIR = ROOT_DIR + '/BASEVIEW'
BUSINESSVIEWS_DIR = ROOT_DIR + '/BUSINESSVIEWS'
CONFIGS_DIR = ROOT_DIR + '/CONFIGS'
DATAS_DIR = ROOT_DIR + '/DATAS'
LOG_DIR = ROOT_DIR + '/LOG'
REPORTS_DIR = ROOT_DIR + '/REPORTS'
SCREENSHOTS_DIR = ROOT_DIR + '/SCREENSHOTS'
TEST_CASES_DIR = ROOT_DIR + '/TEST_CASES'
TEST_RUN_DIR = ROOT_DIR + '/TEST_RUN'
TESTS_DIR = ROOT_DIR + '/TESTS'
